{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"snowball_output\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "5868300c-caa4-4606-827a-96ebec7984fc",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_200ad3b0-2677-4406-9fb4-aa0645d2a181"
      },
      {
        "name": "28534086-6dfc-49d6-9852-d94e39d3a70c",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_850bfd31-48d2-4a9d-98c3-87c5c52c83b8"
      },
      {
        "name": "a460c2fe-7707-48ad-9239-a3873d4649e8",
        "fromColumn": "EOW - Saturday",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3e758989-f869-48a6-9f64-86896ccddf64"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9053d9f-5f89-4f3f-add7-a976af6ef1c5",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b62cd9cb-7ab6-4293-8c65-96fe1542d02b",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "873daae0-b0d8-45ad-95e6-8d2448a2f179",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "3e08bbe8-97f5-4775-9214-3eecd21727f8",
            "sourceColumn": "month_roll",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_200ad3b0-2677-4406-9fb4-aa0645d2a181"
                },
                "isDefault": true,
                "relationship": "5868300c-caa4-4606-827a-96ebec7984fc"
              }
            ]
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03137dbe-9d47-4f80-b083-e9b6f8117fef",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2b62093-2e74-4ada-a311-8e8733a436be",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b60c47c0-49e6-44c1-84c8-33787424c0fb",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4212db20-72e7-48ed-96a4-a656da2a9c64",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4002fed8-5291-48b7-bae9-c9a2abfbf123",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c418dad8-ecaa-4a10-8839-add46e8685fd",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "052531df-bdb0-4c44-b29d-7e508d0e89b5",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "374bb00f-d100-4d9f-bcab-ac43ef9ff4f2",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "83ff7a5b-bf26-47b9-b853-b580d9321a89",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d434c518-07c1-4387-b7c7-0c03eb884dae",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e3fe1ba0-226d-4c0a-bd67-b59b06f9dfe8",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f287e054-53d4-448d-89f4-e860964df887",
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\GokulakrishnanK\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([month_roll] = #date(2020, 1, 1) or [month_roll] = #date(2020, 2, 1) or [month_roll] = #date(2020, 3, 1) or [month_roll] = #date(2020, 4, 1) or [month_roll] = #date(2020, 5, 1) or [month_roll] = #date(2020, 6, 1) or [month_roll] = #date(2020, 7, 1) or [month_roll] = #date(2020, 8, 1) or [month_roll] = #date(2020, 9, 1) or [month_roll] = #date(2020, 10, 1) or [month_roll] = #date(2020, 11, 1) or [month_roll] = #date(2020, 12, 1) or [month_roll] = #date(2021, 1, 1) or [month_roll] = #date(2021, 2, 1) or [month_roll] = #date(2021, 3, 1) or [month_roll] = #date(2021, 4, 1) or [month_roll] = #date(2021, 5, 1) or [month_roll] = #date(2021, 6, 1)))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_46c6befc-ddb4-41cd-9e9d-e2a50308bb8a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "39cde8f6-a2ff-4ff7-9f1d-7be40f3a1123",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "808dbdd0-7538-48ed-a9ef-38285502c44a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bfc34465-f8db-4e9a-91d1-8d0260d3a878",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "569ffe6c-9fd7-48c3-8644-14fc5752704d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0dbd523f-d0ee-4049-a1ae-f329b80e3831",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6cd4794f-f6b7-47d9-956a-60d9c9e1303b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "78026b0f-15eb-4577-b303-b11ee111dd8c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5490d40c-73a0-4a78-8001-7c828e53d1c8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6ea0341f-9380-493e-be45-4b035194c78c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5b5697d8-9b8f-4ebe-9ce1-dd643bf155df",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4568be69-0f8a-4c26-b9b7-ac7c72643737",
                "ordinal": 3
              }
            ],
            "lineageTag": "1b29a01f-1dd9-42b9-bc47-efd7b81deeee"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "cc99ed5e-a93b-4d43-ab94-71a8b3b257a6",
        "partitions": [
          {
            "name": "DateTableTemplate_46c6befc-ddb4-41cd-9e9d-e2a50308bb8a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_200ad3b0-2677-4406-9fb4-aa0645d2a181",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "219d8eaf-9485-44d9-9ad8-aa360982a42b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "05f490df-4b6d-46ed-8eac-107417f6ba34",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f4c489b6-efff-4789-9cc1-d067490cb8f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "84f707b3-068e-4a8f-ab41-b07984feedba",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ba6be002-ba02-492b-b6c6-fd2b778cc323",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9f28783e-ff5a-427e-86e4-ce6a7ae44979",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "87dd8de5-4687-4fb0-b35f-96470e9f2151",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "af5353b3-992a-4534-aea9-6115c69003ec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a654c891-eeca-42ec-a51a-02457ea9b809",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "96cdef4d-ee00-4f83-a64c-d62caea28240",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ec97e158-9321-44db-8a68-cc942f6d1b47",
                "ordinal": 3
              }
            ],
            "lineageTag": "ee3d6cb7-5856-4d31-b263-1ce417ef17ae"
          }
        ],
        "isHidden": true,
        "lineageTag": "60d77ba0-415e-4187-ab03-cf6e8b396012",
        "partitions": [
          {
            "name": "LocalDateTable_200ad3b0-2677-4406-9fb4-aa0645d2a181",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('snowball_output'[month_roll])), 1, 1), Date(Year(MAX('snowball_output'[month_roll])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "85023cdf300b44bf978bb6ad217a7acd"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "662e9571-3110-4052-b7bb-a0c2a940eccc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_850bfd31-48d2-4a9d-98c3-87c5c52c83b8"
                },
                "isDefault": true,
                "relationship": "28534086-6dfc-49d6-9852-d94e39d3a70c"
              }
            ]
          },
          {
            "name": "DateAsInteger",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "543e27cc-3b5d-4a03-b0e1-a84c4b41f941",
            "sourceColumn": "[DateAsInteger]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "669b3bf0-e9e4-4c09-ada2-c944ec9be8cb",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year less 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cddabccd-926d-4dce-925b-f5232fa741f5",
            "sourceColumn": "[Year less 1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2acc2e33-5e60-4bdc-959d-51167d0111e4",
            "sourceColumn": "[MonthYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "32b03dd7-5c93-433a-9157-b7b09e1d86a0",
            "sourceColumn": "[QuarterYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5b6ad3b0-183a-4446-bf4d-f782e89fcf8c",
            "sourceColumn": "[MonthNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a9bef65d-c9c1-45db-af97-7baf82a40d7f",
            "sourceColumn": "[MonthText]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "361274e1-d6de-4fe3-9ebf-1d5686504e52",
            "sourceColumn": "[YearMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YMInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8ae1b77d-57eb-4d1d-b2ba-5d511a810925",
            "sourceColumn": "[YMInt]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekdayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "03e48a44-5315-47ff-aa3e-c586a4b3b6d0",
            "sourceColumn": "[WeekdayNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year & Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b95c2caf-471e-4b12-9cb0-7038748c459f",
            "sourceColumn": "[Year & Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a2573ae0-08ab-4971-aa47-e6b478dcca2c",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5a26a7f1-90e0-4866-8c60-9cd97a37214e",
            "sourceColumn": "[WeekNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "EOW - Saturday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1c288e72-5852-4364-ab8a-76c2d426f288",
            "sourceColumn": "[EOW - Saturday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3e758989-f869-48a6-9f64-86896ccddf64"
                },
                "isDefault": true,
                "relationship": "a460c2fe-7707-48ad-9239-a3873d4649e8"
              }
            ]
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "61835b62-9deb-4776-881c-52385e72286f",
            "sourceColumn": "[Weekday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d20a1774-7ab9-4b06-85cf-31bfe35d3ab4",
            "sourceColumn": "[DayNo]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0df6e7bc-5ab6-4e28-b116-867720ed3b03",
            "sourceColumn": "[DayMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f88ccc77-e425-4ef4-b5ef-dfe979f50e64",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(CALENDAR(date(2017,01,01),date(2026,12,31)),",
                "\"DateAsInteger\", FORMAT ( [Date], \"YYYYMMDD\" ), ",
                "\"Year\", FORMAT([Date], \"yyyy\"), ",
                "\"Year less 1\", FORMAT([Date], \"yyyy\")-1,",
                "\"MonthYear\", FORMAT([Date],\"mmm yy\"),",
                "\"QuarterYear\", FORMAT([Date],\"yyyy \\QQ\"), ",
                "\"MonthNo\", MONTH([Date]),",
                "\"MonthText\", FORMAT([Date], \"mmm\"),",
                "\"YearMonth\", FORMAT([Date], \"MMMM-YYYY\"),",
                "\"YMInt\", 13 * YEAR([Date]) + MONTH([Date]),",
                "\"WeekdayNo\", WEEKDAY([Date],2),",
                "\"Year & Month\", FORMAT([Date],\"MMM-YY\"),",
                "\"Month\", FORMAT([Date], \"mmmm\"), ",
                "\"WeekNo\", WEEKNUM([Date]),",
                "\"EOW - Saturday\", [Date]+7-WEEKDAY([Date]-7),",
                "\"Weekday\", FORMAT([Date], \"dddd\"), ",
                "\"DayNo\", FORMAT([Date], \"d\"),",
                "\"DayMonth\", FORMAT([Date], \"dd mmm\")",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_850bfd31-48d2-4a9d-98c3-87c5c52c83b8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0264cdfe-2e6d-4617-a82f-dfa1d6294111",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "238ed862-94ad-4d10-9eac-eb85953ea3ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5a7d3375-05f9-4338-adf1-6b99eef78e44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "58057e80-3bc6-4e1e-b4cf-b3264e25e6a1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24f14457-0cc3-4c04-8f83-f14ca62245aa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8f7d2050-cb25-463d-9d48-70e70b230baf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7dd95b37-eb3a-4fa0-b0d3-bb543b26b29b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f2521851-d567-4d5e-a25a-754fd2027955",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f024e1ab-22f8-4787-9253-8da10d85ba40",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "52dbf1f5-524b-4f59-9b75-54d94c284577",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "59949b56-6ef9-4b69-b06e-94da6fc7948e",
                "ordinal": 3
              }
            ],
            "lineageTag": "91fc597e-4b0f-4e8d-ac3b-a4398a148bc8"
          }
        ],
        "isHidden": true,
        "lineageTag": "388d61bb-f26e-4077-838d-70df540dbb9c",
        "partitions": [
          {
            "name": "LocalDateTable_850bfd31-48d2-4a9d-98c3-87c5c52c83b8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3e758989-f869-48a6-9f64-86896ccddf64",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "72e8d75c-a05c-498d-908c-34c38e7eff8d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0ab7b789-38fb-409e-b7a0-0b6a9eef877a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a0fdf8b-44fa-4a9b-a3cd-00cc93b6b804",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8869ccb4-2fe2-4477-8b8c-210fd778fa57",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ec00a24-2f86-4751-a72b-f31806cb418b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a79f324b-5182-4170-ba99-df4238231c41",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2d84518-2bf9-4cf7-a8a2-3363309833be",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "660dcedb-4364-44b2-933d-8d5eeedfcd47",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "97b455c6-7972-424e-905d-5eba8372c48c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c9473e26-bf06-4c82-878a-843a67607823",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b6cda026-14db-42b8-af8a-f1fe3ac54934",
                "ordinal": 3
              }
            ],
            "lineageTag": "d5e9b969-7b72-42ee-b7fd-f9bd3e138954"
          }
        ],
        "isHidden": true,
        "lineageTag": "2e29382c-2b0b-4885-aec5-6ca93c960fb7",
        "partitions": [
          {
            "name": "LocalDateTable_3e758989-f869-48a6-9f64-86896ccddf64",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[EOW - Saturday])), 1, 1), Date(Year(MAX('Calendar'[EOW - Saturday])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}